version: '3'

services:
  app:
    container_name: inventory-frontend
    build:
      context: ./inventory-management-app
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      BACKEND_URL: 'http://backend:5179'
    networks:
      - ims-network

  backend:
    container_name: inventory-backend
    build:
      context: ./Inventory_Management_System
    ports:
      - "5179:5179"
    networks:
      - ims-network

networks:
      ims-network:

